### ISSUE TITLE
Weekly Triage meetings: Feb-Jun 2022

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/team-compass#137] opened 2022-02-24 19:56 UTC
This issue contains weekly bug triage meetings, scheduled for either 09:00 PST or 10:00 PST on Thursdays.

HackMD notes: https://hackmd.io/HaQ3S_nPSbqaRtk9rj59iA

Triage issues in jupyterlab and corresponding projects. A major goal at the moment is to triage the Jupyter Notebook background.

Meeting info: https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09

## Goals

Act on long-running, highly demanded, or highly discussed issues to get them ready for development work.

### Resources

https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#submitting-a-pull-request-contribution

### Triage Process

All requested information, where applicable, is provided. From the templates in JupyterLab’s issues:

For a bug:

* Description, preferably including screen shots
* Steps to reproduce
* Expected behavior
* Context, such as OS, browser, JupyterLab version, and output or log excerpts

For a feature request:
* Description of the problem
* Description of the proposed solution
* Additional context

The issue should represent real, relevant, feasible work. In short, if a knowledgeable person were to be assigned this issue, they would be able to complete it with a reasonable amount of effort and assistance, and it furthers the goals of the Jupyter project.

* Issues should be unique; triage is the best time to identify duplicates.
* Bugs represent valid expectations for use of Jupyter products and services.
* Expectations for security, performance, accessibility, and localization match generally-accepted norms in the community that uses Jupyter products.
* The issue represents work that one developer can commit to owning, even if they collaborate with other developers for feedback. Excessively large issues should be split into multiple issues, each triaged individually, or into team-compass issues to discuss more substantive changes.

1. read issues
2. tag issues
    a. good first issue
    b. bug
    c. feature parity
    d. tag milestones
5. identify duplicates
6. respond to issues
7. assign another person

add milestone if you can acheive the goal

### Thursdays @ 10:00–12:00 AM PST (18:00–19:00 UTC)

Primary focus:

* JupyterLab untriaged issues
    * https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3ANeeds+Triage%22
* Jupyter Notebook issues
    * https://github.com/jupyter/notebook/issues
    * keep track of work
    * retro moves into the notebook codebase
        * existing issues might be fixed by retro
    * label issues with NB6/NB7

**Comment by jweill-aws** [comment] 2022-02-24 19:57
### February 3, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Paul Ivanov | Noteable | @ivanov |
| Piyush Jain| AWS | @3coins |
| Zach Sailer | Apple | @Zsailer | 
| Jeremy Tuloup | QuantStack | @jtpio |
| Fabio Pliger | Anaconda | @fpliger |
| tonyfast | Quansight | @tonyfast |
| A. T. Darian  | Two Sigma | @afshin |

#### Agenda

* one triage example
* breakout rooms for projects if more than xx folks

#### Triaged Issues

* https://github.com/jupyter/notebook/issues/534
* https://github.com/jupyter/notebook/issues/1647
* https://github.com/jupyter/notebook/issues/3170
* https://github.com/jupyter/notebook/issues/641
* https://github.com/jupyter/notebook/issues/1524
* https://github.com/jupyter/notebook/issues/4761

**Comment by jweill-aws** [comment] 2022-02-24 19:57
### February 10, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Tony Fast | Quansight  | @tonyfast |
| Jason Weill | AWS | @jweill-aws |
| Zach Sailer | Apple | @Zsailer |
| Piyush Jain | AWS | @3coins |
| | | |


#### Agenda

* triage notebook issues by filter
* triage lab issues https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3ANeeds+Triage%22
* deduplicating issues 
* When accepting an issue, not necessary to apply a milestone

#### Triaged Issues

In `jupyter/notebook`
* [[feature request] add "Pause" button to Notebook #2363](https://github.com/jupyter/notebook/issues/2363) (closed)
* [Horizontal scroll bar behavior in single line cell #2432](https://github.com/jupyter/notebook/issues/2432) (closed)
* [How to deal with chrome failing to launch GPU process #2836](https://github.com/jupyter/notebook/issues/2836) (closed)
* [Kernel crashes with ModuleNotFoundError on 'prompt_toolkit.formatted_text' #4050](https://github.com/jupyter/notebook/issues/4050) (closed)
* [Menu Option to Disable Auto Close Brackets #2650](https://github.com/jupyter/notebook/issues/2650) (closed)
* [Exporting a single jupyter cell output #3039](https://github.com/jupyter/notebook/issues/3039) (enhancement)
* [Bash cells show no intermediate output #2023](https://github.com/jupyter/notebook/issues/2023) (closed)
* [is it possible to make a jupyter notebook run even if the page is closed? #2446](https://github.com/jupyter/notebook/issues/2446) (closed)
* [Feature Request: Enhanced Markdown Support For Graphs #2300](https://github.com/jupyter/notebook/issues/2300) (closed)
* [Running `jupyter notebook` opens visual studio code, not a browser #4304](https://github.com/jupyter/notebook/issues/4304)
* [ENH: allow Markdown footnotes #1287](https://github.com/jupyter/notebook/issues/1287)
* [Run cells in different threads #1155](https://github.com/jupyter/notebook/issues/1155) (closed)
* [Can't paste two images from clipboard in markdown cell #3182](https://github.com/jupyter/notebook/issues/3182) (closed)
* [Restarted computer, can no longer reach kernel #4399](https://github.com/jupyter/notebook/issues/4399) (closed)
* [Multiple notebook to one kernel? #1699](https://github.com/jupyter/notebook/issues/1699) (closed)
* [support for emoji? #2199](https://github.com/jupyter/notebook/issues/2199) (closed)
* [Launching notebook to browser on WSL #4594](https://github.com/jupyter/notebook/issues/4594) (closed)
* [Jupyter does not work with Grammerly #5123](https://github.com/jupyter/notebook/issues/5123) (closed)

In `jupyterlab/jupyterlab`:
* [Hide Contextual Help #12021](https://github.com/jupyterlab/jupyterlab/issues/12021) (accepted)

**Comment by jweill-aws** [comment] 2022-02-24 19:57
### February 17, 2022

Starting with this meeting, the start time was moved from 09:00 PST to 10:00 PST.

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Fabio Pliger| Anaconda | @fpliger |
| Piyush Jain | AWS | @3coins |
| | | |


#### Agenda

* First meeting at the new time of 10:00 AM PST, moved later to accommodate the extended Jupyter Server meeting with collaborative coding from 9:00–10:00 AM PST
* triage notebook issues by filter
* triage lab issues https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3ANeeds+Triage%22
* deduplicating issues 
* When accepting an issue, not necessary to apply a milestone

#### Triaged Issues

In `jupyterlab`:

https://github.com/jupyterlab/jupyterlab/issues/11910
https://github.com/jupyterlab/jupyterlab/issues/12018
https://github.com/jupyterlab/jupyterlab/issues/12039
https://github.com/jupyterlab/jupyterlab/issues/12070 (accepted)
https://github.com/jupyterlab/jupyterlab/issues/12071 (duplicate)
https://github.com/jupyterlab/jupyterlab/issues/12073 (accepted)
https://github.com/jupyterlab/jupyterlab/issues/12079 (accepted)

In `jupyter/notebook`:
https://github.com/jupyter/notebook/issues/534
https://github.com/jupyter/notebook/issues/6284 (answered)
https://github.com/jupyter/notebook/issues/6282 (accepted)
https://github.com/jupyter/notebook/issues/6281 (need input from Steven S.)
https://github.com/jupyter/notebook/issues/6277 (added comments on Discourse)
https://github.com/jupyter/notebook/issues/6274 (referred to colab repo)

**Comment by jweill-aws** [comment] 2022-02-24 19:58
### February 24, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Fabio Pliger | Anaconda | @fpliger |
| Eric Charles | | |
| Jeremy Tuloup | QuantStack | @jtpio |

#### Agenda

Triaged issues:

In `jupyterlab/jupyterlab`:
* https://github.com/jupyterlab/jupyterlab/issues/11910 (asked question of original poster)
* https://github.com/jupyterlab/jupyterlab/issues/12106 (follow up by Eric Charles)
* https://github.com/jupyterlab/jupyterlab/issues/12111 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12113 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12114 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12115 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12117 (accepted)

In `jupyter/notebook`:
* https://github.com/jupyter/notebook/issues/6256 (added comment)

**Comment by jweill-aws** [comment] 2022-03-03 18:54
### March 3, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |

#### Agenda

No attendees this week; I decided to do triage ad hoc

As of meeting start, there are 18 open issues in JupyterLab that need triage.

Triaged issues:

In `jupyterlab/jupyterlab`:
* https://github.com/jupyterlab/jupyterlab/issues/11910 — Still needs info
* https://github.com/jupyterlab/jupyterlab/issues/12106 — Closing in favor of issues that @echarles opened
* https://github.com/jupyterlab/jupyterlab/issues/12113 — Added comment
* https://github.com/jupyterlab/jupyterlab/issues/12124 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12126 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12127 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12132 — Accepted, converted from enhancement to bug
* https://github.com/jupyterlab/jupyterlab/issues/12139 — Needs info
* https://github.com/jupyterlab/jupyterlab/issues/12142 — Left in triage (no Windows computer available for reproduction)
* https://github.com/jupyterlab/jupyterlab/issues/12146 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12151 — Needs info (@fcollonval asked questions)
* https://github.com/jupyterlab/jupyterlab/issues/12152 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12154 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12155 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12157 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12158 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12159 — Accepted
* https://github.com/jupyterlab/jupyterlab/issues/12160 — Accepted

**Comment by jweill-aws** [comment] 2022-03-10 19:07
### March 10, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Jeremy Tuloup | QuantStack | @jtpio |
| Piyush Jain | AWS | @3coins |
| Michał | Oxford | @krassowski |


#### Agenda

As of meeting start, there are [15 open issues in JupyterLab that need triage](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage).

Issues triaged in JupyterLab:
* https://github.com/jupyterlab/jupyterlab/issues/11910 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12113 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12142 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12151 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12164 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12165 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12172 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12174 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12177 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12178 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12180 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12182 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12184 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12185 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12188 (accepted)

Currently 43 issues in RetroLab, most over a week old. Move over to jupyter/notebook as part of the Jupyter Notebook 7 transition from RetroLab?
* We may need to move `retrolab` from `jupyterlab` to `jupyter` so that we can transfer issues within the `jupyter` project (low risk)
* [Discussed yesterday at notebook meeting](https://github.com/jupyter/notebook-team-compass/issues/5#issuecomment-1063740338)

Should we start applying the `status:Needs Triage` tag to new issues to Jupyter Notebook? Currently low volume (only 7 issues in the last month), but may increase as RetroLab is folded in.

Shortcut UI extension — sunset, move issues out

Jupyter Desktop — should we continue to accept issues? Triage process?

**Comment by jweill-aws** [comment] 2022-03-17 17:54
### March 17, 2022

:four_leaf_clover: 

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Jeremy Tuloup | QuantStack | @jtpio |
| Piyush Jain | AWS | @3coins |
| Vidar T Fauske | JP Morgan Chase | @vidartf |
| Jessica Xu | Jupyter community| @jess-x |
| A. T. Darian | Two Sigma | @afshin |

As of meeting start, there are [11 open issues in JupyterLab that need triage](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage).

Issues triaged in JupyterLab:
* https://github.com/jupyterlab/jupyterlab/issues/12151 — needs info
* https://github.com/jupyterlab/jupyterlab/issues/12164 — needs info
* https://github.com/jupyterlab/jupyterlab/issues/12184 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12194 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12196 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12197 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12200 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12201 — closed (by design)
* https://github.com/jupyterlab/jupyterlab/issues/12221 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12222 — accepted
* https://github.com/jupyterlab/jupyterlab/issues/12223 — accepted

Still no "new" option to create an issue in Notebook — https://github.com/jupyter/notebook-team-compass/issues/7 — so there are no new Notebook issues.

Move RetroLab issues into Notebook repo? To discuss next week at Notebook meeting.

**Comment by jweill-aws** [comment] 2022-03-24 17:50
### March 24, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Piyush Jain | AWS | @3coins |
| Martha Cryan | IBM | @marthacryan |
| Rahul Goyal | AWS | @rahul26goyal |

#### Agenda

As of meeting start, there are [13 open issues in JupyterLab that need triage](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage).

Issues triaged:
* https://github.com/jupyterlab/jupyterlab/issues/12151 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12164 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12235 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12236 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12237 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12242 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12246 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12252 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12254 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12263 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12267 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12270 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12272 (accepted)

As of the end of the meeting, there are no open issues in JupyterLab that need triage. :clap:

**Comment by fcollonval** [comment] 2022-03-30 06:32
I updated the title to align with the one of the JupyterLab meeting and pinned the issue to ease retrieval.

**Comment by jweill-aws** [comment] 2022-03-31 18:13
### March 31, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Alex Bozarth | IBM | @ajbozarth |
| Michał Krassowski | Oxford | @krassowski |
| Martha Cryan | IBM | @marthacryan |
| Piyush Jain | AWS | @3coins |

#### Agenda

10 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 2 remain in needs triage.

Triaged issues in `jupyterlab`:
* https://github.com/jupyterlab/jupyterlab/issues/12283 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12284 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12286 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12292 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12294 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12298 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12305 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12307 (closed, fixed)
* https://github.com/jupyterlab/jupyterlab/issues/12308 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12312 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12316 (accepted)

Triaged issues in `jupyterlab-desktop`. Items moved to `jupyterlab` have been cleared of the "Needs Triage" label.
* https://github.com/jupyterlab/jupyterlab-desktop/issues/417 (closed)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/436 (needs info)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/405 (needs info)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/411 (moved to `jupyterlab`)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/410 (accepted)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/380 (moved to `jupyterlab`)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/376 (accepted)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/398 (closed)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/394 (closed, duplicate)

**Comment by jweill-aws** [comment] 2022-04-07 17:54
### April 7, 2022

#### Attendees

| name | organization | username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Jeremy Tuloup | QuantStack | @jtpio |
| Alex Bozarth | IBM | @ajbozarth |

#### Agenda

11 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 2 remain in needs triage.

#### Issues triaged

`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12286 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12315 (duplicate of https://github.com/jupyterlab/jupyterlab/issues/3224)
* https://github.com/jupyterlab/jupyterlab/issues/ (duplicate of https://github.com/jupyterlab/jupyterlab/issues/7006)
* https://github.com/jupyterlab/jupyterlab/issues/12321 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12322 (accepted, help wanted)
* https://github.com/jupyterlab/jupyterlab/issues/12323 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12325 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12330 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12335 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12355 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12375 (accepted)

`jupyterlab-desktop`
* https://github.com/jupyterlab/jupyterlab-desktop/issues/438 (accepted)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/437 (accepted)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/436 (needs info)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/410 (accepted)
* https://github.com/jupyterlab/jupyterlab-desktop/issues/388 (accepted)

**Comment by jweill-aws** [comment] 2022-04-14 17:41
### April 14, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Afshin T. Darian | QuantStack | @afshin |

#### Agenda

10 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 2 remain in Needs Triage.

#### Issues triaged

`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12286 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12330 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12382 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12386 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12388 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12390 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12400 (needs discussion)
* https://github.com/jupyterlab/jupyterlab/issues/12401 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12402 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12408 (accepted)

**Comment by jweill-aws** [comment] 2022-04-21 18:40
### April 21, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Afshin T. Darian | QuantStack | @afshin |

#### Agenda

14 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 1 remains in Needs Triage.

#### Issues triaged
`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12151 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12388 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12400 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12422 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12424 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12433 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12425 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12426 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12432 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12436 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12437 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12443 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12446 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12449 (accepted)

**Comment by jweill-aws** [comment] 2022-05-05 21:19
### May 5, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Piyush Jain | AWS | @3coins |
| Afshin T. Darian | QuantStack | @afshin |
| Adam Patterson | | |
| David Brochart | | |

#### Agenda

13 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 5 remain in Needs Triage.

#### Issues triaged
`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12151 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12479 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12482 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12484 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12488 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12489 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12492 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12504 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12523 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12524 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12530 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12531 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12536 (needs info)

**Comment by jweill-aws** [comment] 2022-05-12 18:43
### May 12, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| A. T. Darian | QuantStack | @afshin |
| Rosio Reyes | Anaconda | @RRosio |
| Jessica Xu | n/a| @jess-x |

#### Agenda

18 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 2 of these remain in Needs Triage.

New comment on jupyterlab-desktop#436: https://github.com/jupyterlab/jupyterlab-desktop/issues/436#issuecomment-1124044939

#### Issues triaged
`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12482 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12504 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12530 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12531 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12536 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12539 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12540 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12542 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12544 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12545 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12546 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12547 (closed, duplicate)
* https://github.com/jupyterlab/jupyterlab/issues/12549 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12557 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12558 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12559 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12561 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12566 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12568 (accepted)


`jupyterlab-desktop`
* https://github.com/jupyterlab/jupyterlab-desktop/issues/436 (accepted, converted from enhancement to bug)

**Comment by jweill-aws** [comment] 2022-05-26 18:19
### May 26, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| A. T. Darian | QuantStack | @afshin |
| Piyush Jain |AWS  | @3coins |
| Rosio Reyes  | Anaconda | @RRosio |

#### Agenda

9 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 1 of these remains in Needs Triage.

We also looked at the oldest issues tagged with `status:Needs Discussion`, closing 5. We closed 3 newer issues as duplicates of accepted issues that had `status:Needs Discussion` tags.

"Accepted" means that the label listed below has been removed because we no longer consider it necessary.

#### Issues triaged
`jupyterlab` (`status:Needs Triage` label)
* https://github.com/jupyterlab/jupyterlab/issues/12531 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12603 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12605 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12607 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12613 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12614 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12615 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12616 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12617 (accepted)

`jupyterlab` (`status:Needs Discussion` label)
* https://github.com/jupyterlab/jupyterlab/issues/113 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/260 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/342 (accepted)
    * https://github.com/jupyterlab/jupyterlab/issues/11791 (closed as duplicate of 342)
* https://github.com/jupyterlab/jupyterlab/issues/600 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/765 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/877 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/1051 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/1072 (accepted)
    * https://github.com/jupyterlab/jupyterlab/issues/8881 (closed as duplicate of 1072)
* https://github.com/jupyterlab/jupyterlab/issues/1371 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/1587 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/1640 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/1932 (accepted)
    * https://github.com/jupyterlab/jupyterlab/issues/12402 (closed as duplicate of 1932)

**Comment by 3coins** [comment] 2022-06-02 18:21
### June 2, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Piyush Jain | AWS | @3coins |

#### Agenda
9 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 1 of these remains in Needs Triage.

#### Issues Triaged
`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12607 (closed as duplicate of [jupyterlite/jupyterlite#119](https://github.com/jupyterlite/jupyterlite/issues/119))
* https://github.com/jupyterlab/jupyterlab/issues/12621 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12622 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12623 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12624 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12628 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12630 (closed as duplicate of [jupyterlite/jupyterlite#119](https://github.com/jupyterlite/jupyterlite/issues/119))
* https://github.com/jupyterlab/jupyterlab/issues/12631 (accepted)

**Comment by jweill-aws** [comment] 2022-06-16 18:57
### June 16, 2022

#### Attendees

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Mike |  | @krassowski  |

#### Agenda
14 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 3 of these remain in Needs Triage.

#### Issues Triaged
`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12622 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12644 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12678 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12681 (closed)
* https://github.com/jupyterlab/jupyterlab/issues/12682 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12684 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12686 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12687 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12688 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12696 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12700 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12702 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12703 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12705 (accepted)

**Comment by jweill-aws** [comment] 2022-06-23 17:34
### June 23, 2022

| Name | Organization | Username |
|------|--------------|----------|
| Jason Weill | AWS | @jweill-aws |
| Piyush Jain | AWS | @3coins |
| | | |
| | | |

#### Agenda
7 issues in [Needs Triage for jupyterlab](https://github.com/jupyterlab/jupyterlab/labels/status%3ANeeds%20Triage). After triaging, 4 of these remain in Needs Triage.

#### Issues Triaged
`jupyterlab`
* https://github.com/jupyterlab/jupyterlab/issues/12688 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12702 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12711 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12717 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12718 (needs info)
* https://github.com/jupyterlab/jupyterlab/issues/12723 (accepted)
* https://github.com/jupyterlab/jupyterlab/issues/12725 (needs info)

**Closed** 2023-01-04 16:20 UTC
Labels: Dev Meeting Minutes
